version: 2

sources:
  - name: silver_data
    # Dùng Jinja đọc thẳng ID dự án từ biến môi trường, bảo mật tuyệt đối!
    database: "{{ env_var('GCP_PROJECT_ID') }}"
    schema: gold_sales
    tables:
      - name: stg_transactions_silver

models:
  - name: daily_revenue
    columns:
      - name: order_date
        tests:
          - not_null
          - unique
      - name: total_revenue
        tests:
          - not_null